#!/usr/bin/env python
# vim: ft=python
"""
Description: Pretty display of RedBrick quota usage
Authors:     Charlie Von Metzradt <phaxx@redbrick.dcu.ie>
             Cian Butler <butlerx@redbrick.dcu.ie>
             Lucas Savva <m1cr0man@redbrick.dcu.ie>
Date:        Sat Oct  8 16:11:42 IST 2005
"""

from __future__ import print_function

import math
import socket
import sys
from os import getuid

# if you change the bar width, you'll also need to change the value in the
# format string in the print statement.
BAR_WIDTH = 35.0


def colour(percent):
    """return colour code for given percentage"""
    if percent > 80:
        return 31  # red
    if percent > 60:
        return 33  # yellow
    return 32  # green


def get_user():
    """get username to look quota for"""
    if len(sys.argv) == 2:
        return sys.argv[1]
    import pwd

    return pwd.getpwuid(getuid())[0]


def convert_size(size_bytes):
    """convert Btye Value to Pretty Value"""
    if size_bytes == 0:
        return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    size_index = int(math.floor(math.log(size_bytes, 1024)))
    return "%s%s" % (
        round(size_bytes / math.pow(1024, size_index), 2),
        size_name[size_index],
    )


def get_quota_from_zfs(username):
    storage_socket = socket.create_connection(("storage.internal", 1995), 1)
    storage_socket.send((username + "\n").encode())
    return storage_socket.recv(1024)


def print_usage(username):
    """output users current usage of storage"""
    raw_quota = get_quota_from_zfs(username)

    if not raw_quota or raw_quota[0] == "-":
        sys.exit(1)

    home = [int(x) for x in raw_quota.decode().strip().split()]
    home.reverse()

    # here's the nasty bit. should really be using a list of filesystems.
    home_percent = 0.0

    if home[1] > 0:
        home_percent = (home[0] * 1.0 / home[1] * 1.0) * 100
    home_bar_width = home_percent * (BAR_WIDTH / 100)

    if home_bar_width > BAR_WIDTH:
        home_bar_width = BAR_WIDTH

    print(
        "Storage space report for %s \033[1;31mRedBrick\033[0m account:\n" % username,
        "%8s: |\033[1;%dm%-35s\033[0m|\033[0;36m%3d\033[0m%%, \033[0;36m%s\033[0m used, \033[0;36m%s\033[0m free"
        % (
            "  storage",
            colour(home_percent),
            "=" * int(home_bar_width),
            home_percent,
            convert_size(home[0]),
            convert_size(home[1] - home[0]),
        ),
    )


if __name__ == "__main__":
    print_usage(get_user())
